name: Build & Deploy ReVanced

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # Optional: run daily at 2:00 UTC
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Build APK
        run: ./gradlew assembleRelease   # Replace with your exact gradle build task

      - name: Collect APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: ReVanced-Release-apk
          path: app/build/outputs/apk/release/*.apk

  deploy:
    name: Deploy Release
    needs: build
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ReVanced-Release-apk
          path: ./release-apks

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: release-apks/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Firebase App Distribution
        if: env.FIREBASE_TOKEN != ''
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ env.FIREBASE_TOKEN }}
          groups: testers
          file: release-apks/*.apk
